### ISSUE TITLE
Broken Links on Website

### ISSUE THREAD

**Issue by Sedoid** [annotorious/project-website-source#33]
I have noticed several broken links on the website that need to be addressed and fixed. 

Here are some examples of broken links I have come across:

The readmore link
![getting_started](https://github.com/annotorious/project-website-source/assets/24408690/94b9b091-5c56-4c9d-bf5c-3738ba4d6a15)

All these
![broken_links](https://github.com/annotorious/project-website-source/assets/24408690/fe200df9-4310-40eb-80a0-d6dd1ba32250)

Annotorious
![guides](https://github.com/annotorious/project-website-source/assets/24408690/3e48d890-8cb3-4908-84e2-91c81894dbe2)

Steps to Reproduce:

Access the [website](https://annotorious.github.io/).
Navigate to the Getting Started.
Click on any link  the  "Read More" section beneath the page.
Observe that it does not direct to the intended page.

**Comment by Sedoid** [comment]
I've cloned and resolved the broken links issues could find, can i submit a PR on this

**Comment by rsimon** [comment]
Ah, awesome - thanks for spotting. And, yes, a PR would be wonderful!

**Comment by Sedoid** [comment]
hello, ive been going through to documentation for hours  how but im unfortunately not able resolve the issue i get.

Description: 
im using these packages below as recommended by the docs in an attempt to perform annotation on an openseadragon image

```
import OpenSeadragon from 'openseadragon';
import * as Annotorious from '@recogito/annotorious-openseadragon';
import '@recogito/annotorious-openseadragon/dist/annotorious.min.css';                   
```

Below is how i initialize OSD so it works Annotorious

```
  const viewerObject = useCallback(
    {
      
      initializeViewer: useCallback(() =>{

          if(viewerRef.current) {

          const viewer = OpenSeadragon({
            id: "home",
            prefixUrl: './images/', // Adjust the path to OpenSeadragon assets
            tileSources: 'http://127.0.0.1:8182/iiif/2/liver.svs/info.json',
            showNavigator: true,
            crossOriginPolicy: "Anonymous",
            disableSelect: false
          });

          const config = {
          };

          const annotate = Annotorious(viewer, config); ............
```

And lastly , call the functions in a useEffect
```
  useEffect(() => {

    viewerObject.initializeViewer()
    return () => {
      viewerObject.destroyViewer()
    };
    
  }, [viewerObject]);

  return ( 
    <>
      <div ref={viewerRef} id="home"> </div>    
    </>

  );
```

This is what i get as the result 

[Video of project behaviour](https://firebasestorage.googleapis.com/v0/b/sama-d512d.appspot.com/o/files%2FKazam_screencast_00007.mp4?alt=media&token=6a161bdf-648b-4fc6-ac22-c2d3bed4a615)

Currentlly, it just draws forever , as soon as i Hold SHIFT key and start selecting an area.. which is good and expected.but the issue is, , it never stops even on mouse release,  it draws and ever stops drawing.,,.. in the end, when i press the ESC key,   it stops drawings and show an error on any other attempt of mouse movement.

**Comment by Sedoid** [comment]
pls, how can i fix this? 

Did i miss a step?

**Comment by rsimon** [comment]
Looks ok. Any error messages on the browser console?

**Comment by Sedoid** [comment]
No, there is no console error during the drag but an error appears when i press ESC key

`ERROR
Cannot read properties of null (reading 'dragTo')
TypeError: Cannot read properties of null (reading 'dragTo')`

**Comment by rsimon** [comment]
Are you doing anything to change the drawing tool programmatically? Are you using specific plugins? Would it be possible for you to set up an online showcase for this, so I can reproduce?

**Comment by Sedoid** [comment]
No, i didn't implement any plugin nor drawing tool,

About the online showcase, is it fine if i push the code to a repository on github and share the link.

its a simple react app with one component.

**Comment by Sedoid** [comment]
[OSD_annotorious_demo](https://github.com/Sedoid/osd_annotorious_demo)

Here it is

**Comment by rsimon** [comment]
BTW `npm install` of your project failed for me, exactly because the build ran into the OSD 2.4/3.0 dependency conflict.

**Comment by Sedoid** [comment]
Thanks, let me try with `npm i openseadragon@3.1.0`

**Comment by Sedoid** [comment]
it works now, Thanks a lot

**Comment by Sedoid** [comment]
do you think the required osd version should be specified somewhere in the docs?
i could add it.

**Comment by rsimon** [comment]
Yes, thanks that would be great. Perhaps on the intro paragraph of https://annotorious.github.io/getting-started/osd-plugin/?

**Comment by Sedoid** [comment]
how about this

![Screenshot from 2023-05-24 10-55-40](https://github.com/annotorious/project-website-source/assets/24408690/e6cd89b9-8b59-4d72-bbf6-32fcb5df1753)

**Comment by Sedoid** [comment]
then i will create an issue and send the pr to it

**Comment by Sedoid** [comment]
or perhaps i just use this same issue

**Comment by rsimon** [comment]
You can just send a PR, doesn't need to reference an issue. Thanks!!
